---

dc_name: backbone
pod_name: pod-backbone

underlay_routing_protocol: ebgp
overlay_routing_protocol: ibgp

switchport_default:
  mode: routed

bgp_peer_groups:
  evpn_overlay_peers:
    structured_config:
      next_hop_unchanged: true
      route_reflector_client: true
      bfd: false
  ipv4_underlay_peers:
    structured_config:
      route_reflector_client: true

type: backbone

backbone:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 1.1.0.0/24
    bgp_as: 65500
    raw_eos_cli: |
      agent KernelFib environment KERNELFIB_PROGRAM_ALL_ECMP='true'
  nodes: 
    - name: BB1
      id: 1 
      mgmt_ip: 192.168.0.9/24 
    - name: BB2
      id: 2
      mgmt_ip: 192.168.0.10/24
