---

fabric_name: FABRIC 

node_type_keys:

  - key: spine
    type: spine
    default_evpn_role: server
    default_ptp_priority1: 20

  - key: l3leaf
    type: l3leaf
    connected_endpoints: true
    default_evpn_role: client
    default_ptp_priority1: 30
    mlag_support: true
    network_services:
      l2: true
      l3: true
    vtep: true

  - key: l2leaf
    type: l2leaf
    connected_endpoints: true
    mlag_support: true
    network_services:
      l2: true
    underlay_router: false
    uplink_type: port-channel

  - key: super_spine
    type: super-spine

  - key: overlay_controller
    type: overlay-controller
    default_evpn_role: server
  
  - key: backbone
    type: backbone
    default_evpn_role: server
    default_overlay_routing_protocol: ibgp
  
  - key: l3spine
    type: l3spine
    connected_endpoints: true
    default_overlay_routing_protocol: none
    default_underlay_routing_protocol: none
    mlag_support: true
    network_services:
      l2: true
      l3: true
    vtep: true
    default_evpn_role: client

  - key: leaf
    type: leaf
    connected_endpoints: true
    mlag_support: true
    network_services:
      l2: true
    underlay_router: false
    uplink_type: port-channel

generate_cv_tags:
  topology_hints: true

mgmt_interface_vrf: default

name_servers:
  - 10.255.0.2

ntp:
  servers:
    - name: 0.pool.ntp.org

local_users: 
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true
  - name: cvpadmin
    privilege: 15
    role: network-admin
    sha512_password: $6$JIWpYntS5KpTMCGF$el6rGKnDYPqxKeMcJGutPctkOMiHrV/bej1DTmdTR8jEnuV/gQbTYa76slNHP1vwyN8Gq2kbNsMmXUwVhkwjy1

cvp_instance_ips:
  - 192.168.0.5
cvp_token_file: /tmp/token
terminattr_disable_aaa: True

custom_structured_configuration_aaa_authorization:
  exec:
    default: local

bgp_graceful_restart:
  enabled: true
  restart_time: 300

bgp_distance:
  external_routes: 20
  internal_routes: 200
  local_routes: 200

default_evpn_encapsulation: vxlan

evpn_import_pruning: true

mlag_ibgp_peering_vrfs:
  base_vlan: 3000

mac_address_table:
  aging_time: 1800

custom_structured_configuration_arp:
  aging:
    timeout_default: 1500
