tenants:
- name: EVPNGW
  mac_vrf_vni_base: 10000
  bgp_peer_groups:
  - name: IPv4-REMOTE-UNDERLAY-PEERS
    nodes:
    - B-LEAF7
    - B-LEAF8
    - C-LEAF7
    - C-LEAF8
    remote_as: 65500
    route_map_out: RM-AS65000-IPV4-OUT
    shutdown: false
  vrfs:
  - name: Prod
    vrf_vni: 50001
    vtep_diagnostic:
      loopback: 101
      loopback_ip_pools:
      - pod: pod-a
        ipv4_pool: 10.101.101.0/27
      - pod: pod-b
        ipv4_pool: 10.101.102.0/27
      - pod: pod-c
        ipv4_pool: 10.101.103.0/27
    mlag_ibgp_peering_ipv4_pool: 192.0.0.0/31
    mlag_ibgp_peering_vlan: 3001
    redistribute_mlag_ibgp_peering_vrfs: false
    svis:
    - id: 10
      name: Blue
      profile: VLAN10
    - id: 20
      name: Green
      profile: VLAN20
    - id: 30
      name: Orange
      profile: VLAN30
    - id: 40
      name: Purple
      profile: VLAN40
    - id: 100
      name: PROD_VLAN100
      ip_address: 10.10.100.1/24
      enabled: true
  - name: Dev
    vrf_vni: 50002
    vtep_diagnostic:
      loopback: 102
      loopback_ip_pools:
      - pod: pod-a
        ipv4_pool: 10.102.101.0/27
      - pod: pod-b
        ipv4_pool: 10.102.102.0/27
      - pod: pod-c
        ipv4_pool: 10.102.103.0/27
    mlag_ibgp_peering_ipv4_pool: 192.0.0.0/31
    mlag_ibgp_peering_vlan: 3002
    redistribute_mlag_ibgp_peering_vrfs: false
    svis:
    - id: 50
      name: Yellow
      profile: VLAN50
    - id: 60
      name: Red
      profile: VLAN60
    - id: 70
      name: Brown
      profile: VLAN70
    - id: 80
      name: Black
      profile: VLAN80
- name: Prod
  mac_vrf_vni_base: 10000
  evpn_l3_multicast:
    enabled: true
    evpn_underlay_l3_multicast_group_ipv4_pool: 232.1.1.1/24
    evpn_underlay_l3_multicast_group_ipv4_pool_offset: -49999
  vrfs:
  - name: Prod
    vrf_vni: 50001
    vtep_diagnostic:
      loopback: 101
      loopback_ip_pools:
      - pod: pod-a
        ipv4_pool: 10.101.101.0/27
      - pod: pod-b
        ipv4_pool: 10.101.102.0/27
      - pod: pod-c
        ipv4_pool: 10.101.103.0/27
    mlag_ibgp_peering_ipv4_pool: 192.0.0.0/31
    mlag_ibgp_peering_vlan: 3001
    redistribute_mlag_ibgp_peering_vrfs: false
    svis:
    - id: 10
      name: Blue
      profile: VLAN10
    - id: 20
      name: Green
      profile: VLAN20
    - id: 30
      name: Orange
      profile: VLAN30
    - id: 40
      name: Purple
      profile: VLAN40
- name: Dev
  mac_vrf_vni_base: 10000
  evpn_l3_multicast:
    enabled: true
    evpn_underlay_l3_multicast_group_ipv4_pool: 232.2.2.1/24
    evpn_underlay_l3_multicast_group_ipv4_pool_offset: -50000
  vrfs:
  - name: Dev
    vrf_vni: 50002
    vtep_diagnostic:
      loopback: 102
      loopback_ip_pools:
      - pod: pod-a
        ipv4_pool: 10.102.101.0/27
      - pod: pod-b
        ipv4_pool: 10.102.102.0/27
      - pod: pod-c
        ipv4_pool: 10.102.103.0/27
    mlag_ibgp_peering_ipv4_pool: 192.0.0.0/31
    mlag_ibgp_peering_vlan: 3002
    redistribute_mlag_ibgp_peering_vrfs: false
    svis:
    - id: 50
      name: Yellow
      profile: VLAN50
    - id: 60
      name: Red
      profile: VLAN60
    - id: 70
      name: Brown
      profile: VLAN70
    - id: 80
      name: Black
      profile: VLAN80
- name: DUALSTACK
  mac_vrf_vni_base: 10000
  vrfs:
  - name: Prod
    vrf_vni: 50001
    mlag_ibgp_peering_vlan: 3001
    redistribute_mlag_ibgp_peering_vrfs: false
    svis:
    - id: 10
      name: Blue
      profile: IPV6_VLAN10
  - name: Dev
    vrf_vni: 50002
    mlag_ibgp_peering_vlan: 3002
    redistribute_mlag_ibgp_peering_vrfs: false
    svis:
    - id: 50
      name: Yellow
      profile: IPV6_VLAN50
    - id: 70
      name: Brown
      profile: IPV6_VLAN70
    - id: 90
      name: Pink
      profile: IPV6_VLAN90
svi_profiles:
- profile: global-svi-profile
  mtu: 9014
  enabled: true
- profile: VLAN10
  parent_profile: global-svi-profile
  ip_address_virtual: 10.10.10.1/24
- profile: VLAN20
  parent_profile: global-svi-profile
  ip_address_virtual: 10.20.20.1/24
- profile: VLAN30
  parent_profile: global-svi-profile
  ip_address_virtual: 10.30.30.1/24
- profile: VLAN40
  parent_profile: global-svi-profile
  ip_address_virtual: 10.40.40.1/24
- profile: VLAN50
  parent_profile: global-svi-profile
  ip_address_virtual: 10.50.50.1/24
- profile: VLAN60
  parent_profile: global-svi-profile
  ip_address_virtual: 10.60.60.1/24
- profile: VLAN70
  parent_profile: global-svi-profile
  ip_address_virtual: 10.70.70.1/24
- profile: VLAN80
  parent_profile: global-svi-profile
  ip_address_virtual: 10.80.80.1/24
- profile: VLAN90
  parent_profile: global-svi-profile
  ip_address_virtual: 10.90.90.1/24
- profile: IPV6_VLAN10
  parent_profile: global-svi-profile
  ip_address_virtual: 10.10.10.1/24
  ipv6_address_virtuals:
  - 2001:db8:10:10::1/64
  ipv6_enable: true
- profile: IPV6_VLAN50
  parent_profile: global-svi-profile
  ip_address_virtual: 10.50.50.1/24
  ipv6_address_virtuals:
  - 2001:db8:50:50::1/64
- profile: IPV6_VLAN70
  parent_profile: global-svi-profile
  ip_address_virtual: 10.70.70.1/24
  ipv6_address_virtuals:
  - 2001:db8:70:70::1/64
  ipv6_enable: true
- profile: IPV6_VLAN90
  parent_profile: global-svi-profile
  ip_address_virtual: 10.90.90.1/24
  ipv6_address_virtuals:
  - 2001:db8:90:90::1/64
  ipv6_enable: true
