---

design:
  type: mpls

# Common AVD group variables
fabric_name: FABRIC

# Define underlay and overlay routing protocol to be used
underlay_routing_protocol: isis-ldp
overlay_routing_protocol: ibgp

# Local users
local_users:
  # Define a new user, which is called "ansible"
  - name: ansible
    privilege: 15
    role: network-admin
    # Password set to "ansible". Same string as the device generates when configuring a username.
    sha512_password: $6$QJUtFkyu9yoecsq.$ysGzlb2YXaIMvezqGEna7RE8CMALJHnv7Q1i.27VygyKUtSeX.n2xRTyOtCR8eOAl.4imBLyhXFc4o97P5n071
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true

# BGP peer groups passwords
bgp_peer_groups:
  # all passwords set to "arista"
  mpls_overlay_peers:
    password: $1c$G8BQN0ezkiJOX2cuAYpsEA==
  rr_overlay_peers:
    password: $1c$G8BQN0ezkiJOX2cuAYpsEA==

management_security:
  password:
    encryption_key_common: true
