hostname: C5
is_deployed: true
service_routing_protocols_model: multi-agent
ip_routing: false
daemon_terminattr:
  cvaddrs:
  - 192.168.0.5:9910
  cvauth:
    method: token
    token_file: /tmp/token
  cvvrf: default
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
spanning_tree:
  mode: none
local_users:
- name: admin
  privilege: 15
  role: network-admin
  no_password: true
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$JIWpYntS5KpTMCGF$el6rGKnDYPqxKeMcJGutPctkOMiHrV/bej1DTmdTR8jEnuV/gQbTYa76slNHP1vwyN8Gq2kbNsMmXUwVhkwjy1
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: 192.168.0.238/24
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true
vlans:
  - id: 20
vlan_interfaces:
  - name: Vlan20
    ip_address: 10.20.20.104/24
port_channel_interfaces:
- name: Port-Channel1
  type: switched
  shutdown: False
  mode: access
  vlans: '20'
ethernet_interfaces:
  - name: Ethernet1
    type: port-channel-member
    channel_group:
      id: 1
      mode: active
  - name: Ethernet2
    type: port-channel-member
    channel_group:
      id: 1
      mode: active
static_routes:
  - vrf: default
    destination_address_prefix: 10.10.10.0/24
    gateway: 10.20.20.1
  - vrf: default
    destination_address_prefix: 10.20.20.0/24
    gateway: 10.20.20.1
  - vrf: default
    destination_address_prefix: 10.30.30.0/24
    gateway: 10.20.20.1
  - vrf: default
    destination_address_prefix: 10.40.40.0/24
    gateway: 10.20.20.1
